/* Generated by Yosys 0.21+7 (git sha1 d98738db5, clang  -fPIC -Os) */

module PLL(Vref, Vout);
  wire _00_;
  wire _01_;
  wire _02_;
  output Vout;
  wire Vout;
  input Vref;
  wire Vref;
  wire \fd0.d0.d ;
  wire \fd0.d0.q ;
  wire \fd0.d1.d ;
  wire \fd0.d1.q ;
  wire \fd0.d2.d ;
  wire \fd0.d2.q ;
  wire \pfd0.DN ;
  wire \pfd0.UP ;
  wire vco_in;
  sky130_fd_sc_hd__inv_1 _03_ (
    .A(\fd0.d2.q ),
    .Y(\fd0.d2.d )
  );
  sky130_fd_sc_hd__inv_1 _04_ (
    .A(\fd0.d1.q ),
    .Y(\fd0.d1.d )
  );
  sky130_fd_sc_hd__inv_1 _05_ (
    .A(\fd0.d0.q ),
    .Y(\fd0.d0.d )
  );
  sky130_fd_sc_hd__nand2_1 _06_ (
    .A(\pfd0.DN ),
    .B(\pfd0.UP ),
    .Y(_00_)
  );
  sky130_fd_sc_hd__inv_1 _07_ (
    .A(Vout),
    .Y(_01_)
  );
  sky130_fd_sc_hd__inv_1 _08_ (
    .A(Vref),
    .Y(_02_)
  );
  sky130_fd_sc_hd__dfxtp_1 _09_ (
    .CLK(\fd0.d1.d ),
    .D(\fd0.d2.d ),
    .Q(\fd0.d2.q )
  );
  sky130_fd_sc_hd__dfxtp_1 _10_ (
    .CLK(\fd0.d0.d ),
    .D(\fd0.d1.d ),
    .Q(\fd0.d1.q )
  );
  sky130_fd_sc_hd__dfxtp_1 _11_ (
    .CLK(_01_),
    .D(\fd0.d0.d ),
    .Q(\fd0.d0.q )
  );
  sky130_fd_sc_hd__dfxtp_1 _12_ (
    .CLK(_02_),
    .D(_00_),
    .Q(\pfd0.UP )
  );
  sky130_fd_sc_hd__dfxtp_1 _13_ (
    .CLK(\fd0.d2.d ),
    .D(_00_),
    .Q(\pfd0.DN )
  );
  CP cp0 (
    .Down(\pfd0.DN ),
    .Out(vco_in),
    .Up(\pfd0.UP )
  );
  VCO vco0 (
    .Clk_Out(Vout),
    .VCtrl(vco_in)
  );
endmodule
